namespace CadTest.Drawing;

/// <summary>Conditional geometric tests, not a recovered surface or permission to cut the body.</summary>
public static class DkRecessAssessment
{
    public const double OpeningDiameter = 33;
    public const double ProfileRadiusMin = 14.9;
    public const double ProfileRadiusMax = 16;
    public const double DepthNominal = 13.5;
    public const double DepthTolerance = 0.35;
    public const double HoleDiameter = 12;
    public const double CentreOffset = 10;

    public static double SphereRadiusForCap(double openingRadius, double depth)
    {
        if (!double.IsFinite(openingRadius) || !double.IsFinite(depth) || openingRadius <= 0 || depth <= 0)
            throw new ArgumentOutOfRangeException(nameof(depth), "Cap radius and depth must be finite and positive.");
        return (openingRadius * openingRadius + depth * depth) / (2 * depth);
    }

    public static object CreateReport() => new
    {
        Source = "chertezh_corrected_final.pdf: A-A, details Д/К",
        Status = "Unresolved surface; no CAD geometry generated by this assessment",
        NominalOpeningDiameterMm = OpeningDiameter,
        ProfileRadiusRangeMm = new[] { ProfileRadiusMin, ProfileRadiusMax },
        AxialDimensionRangeMm = new[] { DepthNominal - DepthTolerance, DepthNominal + DepthTolerance },
        SimpleSphere = new
        {
            Assumption = "Ø33 is a circular section of the same sphere whose radius is R16(-1.1)",
            MaximumSphereDiameterMm = 2 * ProfileRadiusMax,
            Compatible = OpeningDiameter <= 2 * ProfileRadiusMax,
            Explanation = "A sphere with radius at most 16 cannot have a circular section of diameter 33."
        },
        SphericalCap = new
        {
            Assumption = "13.5±0.35 is cap depth and Ø33 is its opening; not established by the drawing review",
            RequiredNominalRadiusMm = SphereRadiusForCap(OpeningDiameter / 2, DepthNominal),
            // Here depth is below opening radius, so required sphere radius decreases as depth increases.
            RequiredRadiusRangeMm = new[] { SphereRadiusForCap(OpeningDiameter / 2, DepthNominal + DepthTolerance),
                SphereRadiusForCap(OpeningDiameter / 2, DepthNominal - DepthTolerance) },
            CompatibleWithProfileRadius = false
        },
        ProjectedHole = new
        {
            Assumption = "Ø12 centre is displaced by 10 toward the bottom of the Ø33 contour",
            NominalRadialGapMm = OpeningDiameter / 2 - CentreOffset - HoleDiameter / 2,
            InferredMainAxisOffsetMm = DrawingRevision.LocalHoleOffset - CentreOffset,
            Explanation = "0.5 is a projected nominal gap, NOT a verified 3D wall thickness; 74 is conditional."
        },
        RemainingWork = new[]
        {
            "Determine whether Ø33 and R16 describe different joined surfaces or a non-spherical surface.",
            "Resolve axial datums and the generating curve against the adjacent right-hand steps.",
            "Check intersections with Ø12 and the rear recess before updating body or volume."
        }
    };

    public static void RunChecks()
    {
        if (Math.Abs(SphereRadiusForCap(16.5, 13.5) - 101.0 / 6) > 1e-12)
            throw new InvalidOperationException("Incorrect spherical cap calculation.");
        for (int i = 0; i <= 1000; i++)
        {
            double depth = DepthNominal - DepthTolerance + 2 * DepthTolerance * i / 1000;
            if (SphereRadiusForCap(16.5, depth) <= ProfileRadiusMax)
                throw new InvalidOperationException("Unexpected compatible simple spherical cap.");
        }
        foreach (double invalid in new[] { 0.0, -1, double.NaN, double.PositiveInfinity })
        {
            bool rejected = false;
            try { SphereRadiusForCap(16.5, invalid); }
            catch (ArgumentOutOfRangeException) { rejected = true; }
            if (!rejected) throw new InvalidOperationException("Invalid cap depth accepted.");
        }
        Console.WriteLine("[TEST OK] Д/К: conditional sphere/cap checks, full depth tolerance interval, invalid inputs.");
    }
}
